version: '3'

services:
  app:
    build: .
    container_name: vue-all-in-one
    network_mode: "host"  # 使用host网络
    restart: unless-stopped
    environment:
      - PORT=5000  # serve 将使用这个端口 
    volumes:
      - ./public/config.yml:/app/config.yml 