services:
  app:
    build: .
    container_name: vue-all-in-one
    network_mode: "host"  # 使用host网络
    restart: unless-stopped
    environment:
      - PORT=5000
      - API_TOKEN_DEV=dev-secret-token
      - API_TOKEN_QA=qa-secret-token 
    volumes:
      - ./public:/app/public 