categories:
  - name: 测试工具
    icon: 'fas fa-screwdriver-wrench'
    links:
      - name: kadmin
        url: https://kadmin.tap4fun.com
        description: kadmin 容器部署管理平台
        icon: 'fas fa-server'
  - name: 文档资源
    icon: 'fas fa-file-lines'
    links:
      - name: GM 指令
        url: >-
          https://docs.google.com/spreadsheets/d/1vCJd9r9Z50uEwwpcUc-5qlCnasPxpDej2YUnHmplf04/edit?gid=0#gid=0
        description: gm 指令记录
        icon: 'fas fa-terminal'
      - name: 配置表
        url: >-
          https://drive.google.com/drive/folders/18fRVYlkXD7hhfQbeYhePDd-upXPF5EyJ
        description: P2所有配置表
        icon: 'fas fa-link'
  - name: 学习资源
    icon: 'fas fa-book'
    links:
      - name: JSON格式
        url: https://www.json.cn
        description: JSON在线编辑
        icon: 'fas fa-file-code'
  - name: 自动化相关
    icon: 'fas fa-robot'
    links:
      - name: wiki
        url: https://wiki.tap4fun.com/display/P2/P2+QA
        description: P2 QA内部知识文档
        icon: 'fas fa-book'
